version: "3"

networks:
  nginx-php74-alpine-mysql57:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
    - "80:80"
    volumes:
    - ./app:/var/www/html
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - nginx-php74-alpine-mysql57

  php:
    image: php:7.4-fpm-alpine
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php74
    volumes:
    - ./app:/var/www/html
    ports:
    - "9000:9000"
    networks:
      - nginx-php74-alpine-mysql57

  mysql:
    image: mysql:5.7
    container_name: mysql57
    restart: always
    ports:
    - "3306:3306"
    volumes:
    - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - nginx-php74-alpine-mysql57